### ISSUE TITLE
Unable to Edit: Missing Dependencies

### ISSUE THREAD

**Issue by RedplagueXIII** [jhlothamer/godot4_visibility_masking_demo#1]
I am attempting to open the project to follow along with the readme.

Downloaded zip file, imported into Godot 4.2.1 and attempted to "edit" (open). Immediately received errors for missing dependents. When attempting to fix missing dependents, it appears that the items are right where they should be.
Receive same error when attempting to open any scene.
Error repeats when first extracting zip file then importing.

Demo will run, but appears to be missing assets.
![vis_test_1](https://github.com/jhlothamer/godot4_visibility_masking_demo/assets/159663772/010a6c70-72a2-45a1-92fc-452d1de985c2)
![vis_test_2](https://github.com/jhlothamer/godot4_visibility_masking_demo/assets/159663772/b2e50402-c63f-49c6-b47d-3ed88f4b8633)
![vis_test_3](https://github.com/jhlothamer/godot4_visibility_masking_demo/assets/159663772/1e72585f-0902-4325-b9ad-a7d45af6a545)

First time commenting on github, please forgive the improper formatting.

Brief snipit of debugger

`Godot Engine v4.2.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
  res://addons/godot_helper_pack/core/2d/util/distribution/distribution_editor_plugin.gd:16 - Parse Error: Could not find type "MultiMeshInstanceDistributionArea" in the current scope.
  res://addons/godot_helper_pack/core/2d/util/distribution/distribution_editor_plugin.gd:17 - Parse Error: Could not find type "RandomDistributionArea" in the current scope.
  res://addons/godot_helper_pack/core/2d/util/distribution/distribution_editor_plugin.gd:21 - Parse Error: Could not find type "MultiMeshInstanceDistributionArea" in the current scope.
  res://addons/godot_helper_pack/core/2d/util/distribution/distribution_editor_plugin.gd:23 - Parse Error: Could not find type "RandomDistributionArea" in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/godot_helper_pack/core/2d/util/distribution/distribution_editor_plugin.gd" with error "Parse error". (User)
  res://addons/godot_helper_pack/godot_helper_pack_plugin.gd:14 - Parse Error: Could not find type "DistributionEditorPlugin" in the current scope.
  res://addons/godot_helper_pack/godot_helper_pack_plugin.gd:19 - Parse Error: Identifier "GodotHelperPackSettings" not declared in the current scope.
  res://addons/godot_helper_pack/godot_helper_pack_plugin.gd:92 - Parse Error: Could not find type "MultiMeshInstanceDistributionArea" in the current scope.
  res://addons/godot_helper_pack/godot_helper_pack_plugin.gd:92 - Parse Error: Could not find type "RandomDistributionArea" in the current scope.
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/godot_helper_pack/godot_helper_pack_plugin.gd" with error "Parse error". (User)
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:3818 - Condition "!_ensure_cache_for_size(fd, size)" is true.
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:2042 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: String()
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:1982 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: String()
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:1962 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: 0
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:2002 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: 400
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:2022 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: 100
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:2042 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: String()
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:1982 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: String()
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:1962 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: 0
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:2002 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: 400
  FreeType: Error loading font: ''.
  modules/text_server_adv/text_server_adv.cpp:2022 - Condition "!_ensure_cache_for_size(fd, size)" is true. Returning: 100
  Ogg Vorbis decoding failed. Check that your data is a valid Ogg Vorbis audio stream.

**Comment by jhlothamer** [comment]
@RedplagueXIII The issue stems from my use of gitlfs and it not working with the Download ZIP feature on github.  I did not realize using gitlfs would cause that.  Can you clone the repository instead?  Be sure to install gitlfs on your machine if you have not already done so.  Otherwise you'll still have an issue.

I plan on updating the readme warning developers about this issue and see if I can add the projects files as an alternative as a release.

**Comment by jhlothamer** [comment]
I've updated the readme to warn about this issue and provided a Release to make a working zip file available.
